### ISSUE TITLE
qdmr 0.10.0 crash when deleting contact in a group list or channel used in a zone

### ISSUE THREAD

**Issue by petrus-lt** [hmatuschek/qdmr#194]
Please consider the very simple codeplug attached to this issue. 

It contains two digital contacts. contained within a group list "test rx group". If you delete one of the two contacts and try to open/edit said group list, qdmr will crash with the following backtrace:

```
(gdb) bt
#0  0x0000000000000061 in  ()
#1  0x00007faec72e84fc in AbstractConfigObjectList::add(ConfigObject*, int) () at /usr/lib/x86_64-linux-gnu/libdmrconf.so.0.10
#2  0x00007faec72e1a8c in AbstractConfigObjectList::copy(AbstractConfigObjectList const&) () at /usr/lib/x86_64-linux-gnu/libdmrconf.so.0.10
#3  0x00007faec72e5bb4 in ConfigItem::copy(ConfigItem const&) () at /usr/lib/x86_64-linux-gnu/libdmrconf.so.0.10
#4  0x0000564e3fa4f742 in RXGroupListDialog::RXGroupListDialog(Config*, RXGroupList*, QWidget*) ()
#5  0x0000564e3fa7739e in GroupListsView::onEditRxGroup(unsigned int) ()
#6  0x00007faec604d1d0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x0000564e3fa8b372 in ConfigObjectListView::doubleClicked(unsigned int) ()
#8  0x0000564e3fa6e69b in ConfigObjectListView::onDoubleClicked(QModelIndex) ()
#9  0x0000564e3fa8b3d2 in  ()
#10 0x00007faec604d1d0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007faec6ef22c9 in QAbstractItemView::doubleClicked(QModelIndex const&) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007faec6f00a25 in QAbstractItemView::mouseDoubleClickEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007faec6cce86b in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007faec6d7bd52 in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007faec6f00482 in QAbstractItemView::viewportEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007faec602151b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007faec6c8ba55 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007faec6c95343 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007faec602180a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007faec6c94457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007faec6cea35d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007faec6ced1ec in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007faec6c8ba66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007faec6c950f0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007faec602180a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007faec665c71c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007faec665e10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007faec663835b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007faec270f32e in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#30 0x00007faec4f6417d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007faec4f64400 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007faec4f644a3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007faec6079435 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007faec60203ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007faec6028116 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x0000564e3fa360ae in main ()
```
The same bug exists with two channels within a zone if you delete one of those channels, when editing the zone qdmr will crash. 

[test_codeplug.yaml.txt](https://github.com/hmatuschek/qdmr/files/7898356/test_codeplug.yaml.txt)

**Comment by hmatuschek** [comment]
Should be fixed now. This bug was likely there since the rewrite to version 0.9.0. In master, there are also some changes to the way radios are detected. Once I've tested that, I'll release 0.10.1 with this fix. However, feel free to test the fix in master anyway.

**Comment by petrus-lt** [comment]
I just compiled with the fix and it looks good, no crash with my full codeplug when deleting a contact or a channel. Many thanks Hannes!
